name: Build and push Docker images
on:
  push:
    paths:
    - 'nix/**'
    - 'flake.nix'
    - 'flake.lock'
    - 'apps/**'
    - 'packages/**'
    - '.dockerignore'
    - '.github/workflows/docker.yml'
    - 'package.json'
    - 'pnpm-lock.yaml'
    - 'pnpm-workspace.yaml'
  workflow_dispatch:

jobs:
  build:
    name: 'nix docker build'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    # temporarily comment this out for testing
    #if: github.repository == 'PluralKit/web'
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main

      - if: ${{ !env.ACT }}
        env:
          OWNER: ${{ github.repository_owner }}
          TAG: ${{ github.sha }}
          REF_NAME: ${{ github.ref_name }}
          ACTOR: ${{ github.actor }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REGISTRY_AUTH_FILE: ${{ runner.temp }}/auth.json
        run: |
          set -euo pipefail
          nix shell nixpkgs#skopeo nixpkgs#jq -c ./ci/build-push-images.sh
